### ISSUE TITLE
Excise ERFA

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/AstroTime.jl#1]
Replace the calls to ERFA by pure Julia functions:

* [ ] `eraD2dtf`
* [X] ~`eraDat`~ #31 
* [X] ~`eraDtdb`~ #14 
* [X] ~`eraDtf2d`~ #36
* [X] ~`eraTaitt`~ #4 
* [X] ~`eraTaiut1`~ #8 
* [X] ~`eraTaiutc`~ ~#13~ #39
* [X] ~`eraTcbtdb`~ #25
* [X] ~`eraTcgtt`~ #9 
* [X] ~`eraTdbtcb`~ #24
* [X] ~`eraTdbtt`~ #14 
* [X] ~`eraTttai`~ #6 
* [X] ~`eraTttcg`~ #10 
* [X] ~`eraTttdb`~ #20
* [X] ~`eraTtut1`~ #21 
* [X] ~`eraUt1tai`~ #7 
* [X] ~`eraUt1tt`~ #22 
* [x] ~`eraUt1utc`~ #40
* [X] ~`eraUtctai`~ ~#15~ #37
* [X] ~`eraUtcut1`~ #38

**Comment by giordano** [comment]
In `AstroLib.jl` there are [some functions](https://juliaastro.github.io/AstroLib.jl/latest/ref.html#Time-and-date-1) for time conversion, but I don't know whether they can be useful here.

**Comment by prakharcode** [comment]
@helgee Can I start with porting of `eraTttai` since I'm done with `eraTaitt` in #4 ?

**Comment by helgee** [comment]
ERFA is officially excised 🎉 Congrats @prakharcode
