### ISSUE TITLE
Epochs during a leap second cannot be printed

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/AstroTime.jl#18]
Printing relies on `Dates` functionality which does not know about leap seconds.

**Comment by prakharcode** [comment]
I'll try to fix this

**Comment by helgee** [comment]
Try this: `UTCEpoch(2016, 12, 31, 23, 59, 60)`

**Comment by helgee** [comment]
Unfortunately I think that there is no easy answer here. We have to deal with several problems.

* Until now we would just convert any `Epoch{T}` to `DateTime`. Whereas the Julia manual states that `DateTime` objects are essentially in UT1. So we should probably convert to a `UT1Epoch` before converting to `DateTime`.
* This does not solve the `show` problem though, since we want to display the timestamp in the original time scale.
* While it would be easy too implement a simple show function based on `d2dtf` would lose all the nicesties of the date formatting functionalities of `Dates`.

I would like to hear your thoughts on this @giordano

**Comment by helgee** [comment]
Fixed by #43
