### ISSUE TITLE
Rename the package to AstroTime.jl?

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/AstroTime.jl#19]

**Comment by giordano** [comment]
Honestly I don't have a strong feeling about this, I'm fine with both names :slightly_smiling_face: However, all other packages in this organization have "astro" instead of the full "astronomical", I guess this is your point.

**Comment by helgee** [comment]
Yup, and "Astronomical" is quite a mouthful.

**Comment by prakharcode** [comment]
Yes! "Astro" serves the same purpose! Yay indeed!
