### ISSUE TITLE
Date of Year Formatting String [Feature Request]

### ISSUE THREAD

**Issue by TestSubjector** [JuliaAstro/AstroTime.jl#2]
Issue JuliaLang/julia#21905 contains a request for a date of year format, almost identical to the 2nd format in [date_conv.pro](https://idlastro.gsfc.nasa.gov/ftp/pro/astro/date_conv.pro) at IDL AstroLib.
Such a feature seems highly suitable to be present in AstronomicalTime.jl

**Comment by helgee** [comment]
Fixed by #43
