### ISSUE TITLE
Use a script to generate leap seconds constants from an LSK kernel

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/AstroTime.jl#32]
We currently download an LSK kernel with leap seconds data once and the parse it on every import. This is not incredibly useful since the download URL will change everytime NAIF publishes a new kernel. In consequence we will need to publish a new release everytime a new leap second is introduced which means that we could also (semi-)hard code leap seconds instead.

I propose to use a Julia script to generate a file with the required constants from an LSK kernel similar to the approach taken by [Chrono.jl](https://github.com/FugroRoames/Chrono.jl). This has the added benefit that AstroTime then does not need to depend on RemoteFiles.jl and OptionalData.jl anymore.

**Comment by omus** [comment]
Would it make sense to make a leap seconds package which both Chrono.jl and AstroTime.jl could use? I'll note that the [TimeZones.jl](https://github.com/JuliaTime/TimeZones.jl) already downloads the tzdata which contains the latest leap second information.

**Comment by prakharcode** [comment]
@omus yes! That's right! A package would be quite useful. @helgee I will try to create a package which will do as you suggested.

**Comment by omus** [comment]
Sounds good to me. If you want to create under the [JuliaTime](https://github.com/JuliaTime) organization I can add create a repo and add members.

**Comment by helgee** [comment]
@omus Please do so and add @prakharcode and me 👍

**Comment by helgee** [comment]
Implemented in https://github.com/JuliaTime/LeapSeconds.jl
