### ISSUE TITLE
porting utctai

### ISSUE THREAD

**Issue by prakharcode** [JuliaAstro/AstroTime.jl#34]
The function is straightforward to implement. `Leapseconds` makes it quite easier. 

Regarding this test
`leap = UTCEpoch(2016, 12, 31, 23, 59, 60)`. I'm a bit unsure, here's what I think, should I subtract the drift from the seconds part because 60 is going out of range. 
@helgee

**Comment by helgee** [comment]
60 is not out of range. When a leap second is applied the preceding minute is by definition one second longer: https://en.wikipedia.org/wiki/Leap_second

**Comment by helgee** [comment]
A UTC clock would read:

* 23:59:59
* 23:59:60
* 00:00:00

**Comment by prakharcode** [comment]
I figured I would need to submit a PR for `dtf2d` before `utctai`. Since it correctly converts the leapseconds. The remote kernel file also provides the instruction: 

> DELTA_AT is always an integral number of seconds. The value of DELTA_AT was 10
seconds in January 1972, and increases by one each time a leap second
is declared.
should I propose for 'dtf2d` first?

**Comment by helgee** [comment]
> should I propose for 'dtf2d` first?

Yes, you are correct. We will need that function first.
