### ISSUE TITLE
Porting dtf2d

### ISSUE THREAD

**Issue by prakharcode** [JuliaAstro/AstroTime.jl#35]
I've done the port and it's working and providing the julian of the particular day. But the `DateTime` is failing to parse the julian date as seconds is going outside the range of DateTime.

I know d2dtf is required to get the julian dates to Gregorian format but still, DateTime would fail.

> since the Date type only resolves to the precision of a single date (i.e. no hours, minutes, or seconds), normal considerations for time zones, daylight savings/summer time, and leap seconds are unnecessary and avoided.

in the Julia [docs](https://docs.julialang.org/en/v0.6.2/manual/dates/).

Do I have to design a new show function?
Any suggestions

**Comment by helgee** [comment]
I have put my thoughts about the `show` problem in #18. This is actually orthogonal to your work here @prakharcode since this issue only occurs at the REPL.
