### ISSUE TITLE
TDB differencing error due to epoch storage

### ISSUE THREAD

**Issue by bgodard** [JuliaAstro/AstroTime.jl#44]
If I have 2 observers on the surface of the Earth take some measurements at a given TT = tt0 and I want to model a combined observation in the barycentric reference system, I can compute TDB1 (for observer 1) and TDB2 (for observer 2) using an accurate position dependent TDB-TT difference model.

```julia
tdb1 = TDBEpoch(tai_offset_observer1,tt0)
tdb2 = TDBEpoch(tai_offset_observer2,tt0)
```
but then:
```julia
julia> tdb2-tdb1
0.0 seconds

julia> tdb2==tdb1
true
```

but both of these are not correct. The assumption that time can be compared independently of timescale is incorrect (simultaneity is a relative concept).

**Comment by helgee** [comment]
Fixed in #45
