### ISSUE TITLE
Incorrect value when using TT time in a range expression

### ISSUE THREAD

**Issue by barrettp** [JuliaAstro/AstroTime.jl#60]
The following range expression produces an incorrect value when using TT time.

>> TTEpoch("2021-05-09T07:01:10"):TTEpoch("2021-05-09T08:02:00")
2021-05-09T07:01:10.000 TT:86400.0 seconds:2021-05-09T07:01:10.000 TT

**Comment by giordano** [comment]
It probably depends on what you expect it to do.  Would you expect both endpoints to be included?  That's not what the `lower:step:upper` syntax does: the lower endpoint is always included, but upper may or may not be included, depending on whether `upper - lower` is an integer multiple of `step`.  If you want to include both endpoints you should look into [`range`](https://docs.julialang.org/en/v1/base/math/#Base.range).

**Comment by barrettp** [comment]
However, the full version of the function returns the result that I expected. The short version apparently assumes units of days, not seconds.

TTEpoch("2021-05-09T07:01:10"):1seconds:TTEpoch("2021-05-09T07:01:20")
2021-05-09T07:01:10.000 TT:1 second:2021-05-09T07:01:20.000 TT

**Comment by helgee** [comment]
I'd say that the current code works as intended, see here: https://github.com/JuliaAstro/AstroTime.jl/blob/master/src/Epochs/ranges.jl#L1

The question is whether the intention is the correct one 😉 I would make sense to change the default unit to seconds, i.e. an SI unit. I am not sure why I chose days in the first place. Probably because I was used to working with Julian Day numbers...

**Comment by barrettp** [comment]
Yes, the code works as intended. The issue is: when you enter a time accurate to the second, I think you would expect the result to be accurate to the second and that was not the case. I would error on the side of greater precision and let the user decide otherwise.

**Comment by giordano** [comment]
It's a fair observation, but I think we don't really have an easy way to tell what precision the user used.  Defaulting to one second probably makes sense, but someone may expect even greater granularity.  As a general remark, when using the `:` syntax I recommend explicitly using the desired step to avoid any surprise (or problems when the default value is changed).

**Comment by barrettp** [comment]
Yes, I had considered the precision argument. My recommendation then is to modify the help document to emphasize using the long form of range operator with the step size, instead of the short form. This can be used to inform the user that the default step size is in days.
