### ISSUE TITLE
RemoteFile version bump to 0.4

### ISSUE THREAD

**Issue by ptiede** [JuliaAstro/AstroTime.jl#61]
Hi

I was wondering if you were planning on bumping the version of RemoteFiles to 0.4. I am having some dependency issues with RemoteFiles and HTTP that require this.

**Comment by helgee** [comment]
Yes, in principle. For the record, could you post the error messages you are receiving?

**Comment by ptiede** [comment]
Sorry about that. My problem is that some packages require RemoteFiles 0.4 so when I try to add it I get the following dependency error:
```
(jl_xpXGd0) pkg> add RemoteFiles@v0.4
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package EarthOrientation [732a3c5d]:
 EarthOrientation [732a3c5d] log:
 ├─possible versions are: 0.3.0-0.7.0 or uninstalled
 ├─restricted by compatibility requirements with AstroTime [c61b5328] to versions: 0.4.0-0.7.0
 │ └─AstroTime [c61b5328] log:
 │   ├─possible versions are: 0.1.0-0.6.2 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.6.2
 └─restricted by compatibility requirements with RemoteFiles [cbe49d4c] to versions: uninstalled — no versions left
   └─RemoteFiles [cbe49d4c] log:
     ├─possible versions are: 0.2.0-0.4.2 or uninstalled
     └─restricted to versions 0.4 by an explicit requirement, leaving only versions 0.4.0-0.4.2
```

**Comment by helgee** [comment]
It's fine. Since I am the maintainer of all three packages (RemoteFiles.jl, EarthOrientation.jl, AstroTime.jl) it seems that I screwed up the `[compat]` entries 🙈

**Comment by helgee** [comment]
EarthOrientation.jl had an old `[compat]` entry for RemoteFiles.jl. Should be fixed now.
